on:
  push:
    branches:    
      - master
    paths:
      - 'doc/**'
  pull_request:
    branches:    
      - master
    paths:
      - 'doc/**'
name: Copy Md
jobs:
  all:
    name: Copy Md
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copyTo
      uses: andstor/copycat-action@v2.0.0
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        src_path: doc/
        dst_path: /projects/
        dst_owner: ArthusLiang
        dst_repo_name: gather