on:
  push:
    branches:    
      - master
    paths:
      - 'doc/**'
  pull_request:
    branches:    
      - master
    paths:
      - 'doc/**'
name: Copy Md
jobs:
  jobZH:
    name: Copy Chinese Documents
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copyTo
      uses: andstor/copycat-action@v2.0.0
      with:
        personal_token: ${{ secrets.copykey }}
        src_path: doc/zh_cn/.
        dst_path: /doc/_posts/zh_cn/gathering
        dst_owner: ArthusLiang
        dst_repo_name: gather
        username: yulhuang
        email: 531151995@qq.com
  jobEN:
    name: Copy English Documents
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copyTo
      uses: andstor/copycat-action@v2.0.0
      with:
        personal_token: ${{ secrets.copykey }}
        src_path: doc/en_us/.
        dst_path: /doc/_posts/en_us/gathering
        dst_owner: ArthusLiang
        dst_repo_name: gather
        username: yulhuang
        email: 531151995@qq.com